# Init
ANTIGEN="$HOME/.config/zsh/antigen.zsh"

if [ ! -f $ANTIGEN ]; then
	echo "Installing antigen ..."
	curl -L "http://git.io/antigen" -o antigen.zsh
fi

source ~/.config/zsh/antigen.zsh
source ~/.config/zsh/defaults
source ~/.config/zsh/alias
source ~/.config/zsh/functions

# Plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle jeffreytse/zsh-vi-mode
antigen bundle skywind3000/z.lua

